[StyleKey]
DynamicVariables=1
UpdateDivider=-1
Shape	=Rectangle [#CURRENTSECTION#Text:X],[r:Y],#ButtonSize#,#ButtonSize# | Fill Color 0,0,0,1 | StrokeWidth 1 | StrokeColor #01ColorScheme#
;Shape = Rectangle [#CURRENTSECTION#:r:X],[#CURRENTSECTION#:r:Y],#ButtonSize#,#ButtonSize# | Fill Color 0,0,0,1 | StrokeWidth 1 | StrokeColor #01ColorScheme#
;Hidden=(#Rows#<#CURRENTSECTION#)?

[StyleKey_Wide]

[StyleKey_Tall]

[StyleScrollWheel]

[StyleThumbStick]

[StyleArrow_Up]

[StyleArrow_Down]

[StyleArrow_Left]

[StyleArrow_Right]

[StyleArrow_UpRight]

[StyleArrow_UpLeft]

[StyleArrow_DownRight]

[StyleArrow_DownLeft]