[Variables]

24,255,37=149,0,26


BaseColor =102,185,51
StartColorScheme=#BaseColor#
StartFont=#BaseColor#
01ColorScheme=#BaseColor#
01Font=#BaseColor#
02ColorScheme=#BaseColor#
02Font=#BaseColor#
03ColorScheme=#BaseColor#
03Font=#BaseColor#
04ColorScheme=#BaseColor#
04Font=#BaseColor#
05ColorScheme=#BaseColor#
05Font=#BaseColor#
06ColorScheme=102,185,51
06Font=#BaseColor#
07ColorScheme=#BaseColor#
07Font=#BaseColor#
08ColorScheme=#BaseColor#
08Font=#BaseColor#
09ColorScheme=#BaseColor#
09Font=#BaseColor#
10ColorScheme=#BaseColor#
10Font=#BaseColor#
11ColorScheme=102,185,51
11Font=#BaseColor#
12ColorScheme=#BaseColor#
12Font=#BaseColor#
13ColorScheme=#BaseColor#
13Font=#BaseColor#
14ColorScheme=#BaseColor#
14Font=#BaseColor#
15ColorScheme=#BaseColor#
15Font=#BaseColor#
16ColorScheme=102,185,51
16Font=#BaseColor#
17ColorScheme=#BaseColor#
17Font=#BaseColor#
18ColorScheme=#BaseColor#
18Font=#BaseColor#
19ColorScheme=#BaseColor#
19Font=#BaseColor#
20ColorScheme=#BaseColor#
20Font=#BaseColor#

ScrollWheelColorScheme=#BaseColor#
ScrollUpColorScheme=#BaseColor#
ScrollDownColorScheme=#BaseColor#
ScrollClickColorScheme=#BaseColor#













ThumbStickColorScheme=#BaseColor#
ThumbUpColorScheme=#BaseColor#
ThumbDownColorScheme=#BaseColor#
ThumbLeftColorScheme=#BaseColor#
ThumbRightColorScheme=#BaseColor#
ThumbUpLeftColorScheme=#BaseColor#
ThumbUpRightColorScheme=#BaseColor#
ThumbDownLeftColorScheme=#BaseColor#
ThumbDownRightColorScheme=#BaseColor#

ButtonColorScheme=#BaseColor#
24,255,37=149,0,26
ScrollWheelClickColorScheme=#BaseColor#
ScrollWheelUpColorScheme=#BaseColor#
