[Variables]
@Include = Settings.inc
 
01ColorScheme=#BaseColor#
02ColorScheme=0,122,134
03ColorScheme=#BaseColor#
04ColorScheme=#BaseColor#
05ColorScheme=#BaseColor#
06ColorScheme=#BaseColor#
07ColorScheme=24,255,37
08ColorScheme=0,200,200
09ColorScheme=#BaseColor#
10ColorScheme=#BaseColor#
11ColorScheme=#BaseColor#
12ColorScheme=149,0,26
13ColorScheme=#BaseColor#
14ColorScheme=#BaseColor#
15ColorScheme=142,156,255
16ColorScheme=#BaseColor#
17ColorScheme=#BaseColor#
18ColorScheme=#BaseColor#
19ColorScheme=#BaseColor#
20ColorScheme=#BaseColor#

ScrollWheelColorScheme=#BaseColor#
ScrollUpColorScheme=#BaseColor#
ScrollDownColorScheme=#BaseColor#
ScrollClickColorScheme=#BaseColor#

ThumbStickColorScheme=#BaseColor#
ThumbUpColorScheme=#BaseColor#
ThumbDownColorScheme=#BaseColor#
ThumbLeftColorScheme=#BaseColor#
ThumbRightColorScheme=#BaseColor#
ThumbUpLeftColorScheme=#BaseColor#
ThumbUpRightColorScheme=#BaseColor#
ThumbDownLeftColorScheme=#BaseColor#
ThumbDownRightColorScheme=#BaseColor#

ButtonColorScheme=#BaseColor#


