[Rainmeter]

[Variables]

[MeasureProfileList]

Measure=Plugin
Plugin=FileView
Path=#ROOTCONFIG#Settings\Profiles
ShowDotDot=0
ShowFile=0
ShowFolder=1
Count=15

[Profile01]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=1


[Profile02]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=2

[Profile03]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=3

[Profile04]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=4

[Profile05]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=5

[Profile06]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=6

[Profile07]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=7

[Profile08]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=8

[Profile09]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=9

[Profile10]
Measure=Plugin
Plugin=FileView
Path=[MeasureProfileList]
Type=FileName
Index=10

